# Generated by Django 5.0.2 on 2024-10-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esporte', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=50)),
                ('qualidade', models.CharField(choices=[('MB', 'Muito boa'), ('B', 'Boa'), ('M', 'Mediana'), ('R', 'Ruim'), ('MR', 'Muito ruim')], max_length=50)),
            ],
        ),
    ]
