# Generated by Django 5.0.2 on 2024-11-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo_rapido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadraGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.URLField(max_length=1000)),
                ('esporte', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=50)),
                ('qualidade', models.CharField(choices=[('MB', 'Muito boa'), ('B', 'Boa'), ('M', 'Mediana'), ('R', 'Ruim'), ('MR', 'Muito ruim')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Quadra',
        ),
    ]
