# Generated by Django 5.1.3 on 2024-11-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogo_rapido", "0004_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadrageral",
            name="horarios_disponiveis",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="quadrageral",
            name="preco_por_hora",
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
    ]
