# Generated by Django 5.1.3 on 2024-12-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogo_rapido", "0006_perfilusuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="favoritos",
            field=models.ManyToManyField(
                blank=True, related_name="favoritado_por", to="jogo_rapido.quadrageral"
            ),
        ),
    ]
